<?xml version="1.0"?>
<package format="3">
  <name>motor_control</name>
  <version>0.1.0</version>
  <description>IRC drive-thru low-level Dynamixel motor control.</description>
  <maintainer email="todo@todo.com">IRC</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>soomac_interfaces</exec_depend>
  <exec_depend>arm_control</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
